name: "${THEME_NAME}"
services:
  wordpress:
    container_name: wp-${THEME_NAME}
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - "../plugins:/var/www/html/wp-content/plugins"
      - "../mytheme:/var/www/html/wp-content/themes/mytheme"
    env_file:
      - ./.env
 
  db:
    container_name: db-${THEME_NAME}
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      WORDPRESS_THEME_NAME: "${THEME_NAME}"
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
