services:
  wordpress:
    container_name: ${THEME_NAME}-wp
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - "./plugins:/var/www/html/wp-content/plugins"
      - "./themes:/var/www/html/wp-content/themes"
    env_file:
      - ./.env
 
  db:
    container_name: ${THEME_NAME}-db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      WORDPRESS_THEME_NAME: "${THEME_NAME}"
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
