#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "✅ commit-msg hook が実行されました！"

TEMPLATE=".github/.gitmessage.txt"

if [ -f "$TEMPLATE" ]; then
  echo
  echo "📝 以下のテンプレートを参考にしてください:"
  echo "---------------------------------------------"
  cat "$TEMPLATE"
  echo "---------------------------------------------"
  echo
else
  echo "⚠️ テンプレートが見つかりませんでした: $TEMPLATE"
fi
